export const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    CLICK_OUTSIDE_CART:'CLICK_OUTSIDE_CART',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_CART_ITEM',
    CLEAR_ITEM: 'CLEAR_ITEM',
    DELETE_ITEMS_AFTER_LOGGEDOUT:'DELETE_ITEMS_AFTER_LOGGEDOUT'
};
