export const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    HIDDEN_VALUE:'HIDDEN_VALUE',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_CART_ITEM',
    CLEAR_ITEM: 'CLEAR_ITEM'
};
